name: Scrape from github
on:
  schedule:
    - cron: "10,40 * * * *"
  workflow_dispatch:

permissions:
  contents: write
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Config Github
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.lock
      - name: Just Do It
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python main.py
          ret=$?
          if (( ret == 0 )); then 
            git add . && git commit -m 'Update: '"$(date)" && git push || echo 'nothing to push'
          else
            echo error
          fi
